export const MESS_ADD_TO_CART = 'MUA THÀNH CÔNG !'
export const MESS_ERROR_TO_CART = 'HẾT HÀNG !'
export const MESS_DELETE_TO_CART = 'XÓA THÀNH CÔNG !'
export const MESS_EMPTY_TO_CART = 'GIỎ HÀNG RỖNG !'
export const MESS_WELCOMES = 'CHÀO MỪNG ĐẾN VỚI   M É L A N I E   !'